# Generated by Django 4.1 on 2024-01-29 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='report',
            options={'permissions': (('can_view_report', 'Can view report'), ('edit_report', 'Can edit report'), ('can_delete_report', 'Can delete report'))},
        ),
        migrations.AddField(
            model_name='report',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
